### ISSUE TITLE
WORKSPACE_ID not defined.

### ISSUE THREAD

**Issue by bjorn-lundin** [TamaMcGlinn/AdaBots#1]
Trying out this cool project I hit a bump

Crash - env-var WORKSPACE_ID not defined.
looking into the code - I cannot see what values it would like.

bnl@tp:~/git/AdaBots_examples/bin$ ./build_house

raised CONSTRAINT_ERROR : a-envvar.adb:208 explicit raise
[./build_house]
0x514196 Ada.Environment_Variables.Value at a-envvar.adb:208
0x425f5a Adabots.Create_Dispatcher at adabots.adb:16
0x426016 Adabots.Create_Turtle at adabots.adb:27
0x426260 Adabots.Create_Turtle at adabots.adb:24
0x40c72f Build_House at build_house.adb:7
0x40d694 Main at b__build_house.adb:772
[/lib/x86_64-linux-gnu/libc.so.6]
0x7f99e0409248
0x7f99e0409303
[./build_house]
0x40c5af _start at ???
0xfffffffffffffffe

so - what is a reasonable value for WORKSPACE_ID?
And what is is?

**Comment by TamaMcGlinn** [comment]
Sorry about this, I should add something to the readme for local installations.

WORKSPACE_ID is how you match up bots on the minetest server to AdaBots client programs running on your machine. Any value is fine, as long as you have defined the same while running your program as the minetest server has. For example, try `WORKSPACE_ID=bjorn_lundin_1 ./bin/test` and start your minetest server with `WORKSPACE_ID=bjorn_lundin_1 minetest`.

There will soon be a signup button on the website that gives you a web based editor and minetest server that are already connected to each other. However, running it locally is free.

**Comment by bjorn-lundin** [comment]
Alright, thanks for that answer.
Now - I just need to figure out how to get that docker I use to understand the env var. Guess I'll need to read up on docker.
Anyway - I got something to help start digging

**Comment by bjorn-lundin** [comment]
Alright - seems easy enough
[https://vsupalov.com/docker-environment-variables-from-host/]
gives some examples like 
`$ docker run -e var_name (...)`

I'll test in the weekend
